const {test}=require('node:test');const assert=require('node:assert/strict');const {newDb,DataType}=require('pg-mem');
const {createStore}=require('../api/_db');const {createAccounts}=require('../lib/accounts');const {createHandlers}=require('../lib/api');const {L}=require('./helpers');
test('accounts: immediate signup, owner protection, permissions, payment, picks, reset, sessions and audit',async()=>{
 const mem=newDb();mem.public.registerFunction({name:'clock_timestamp',returns:DataType.timestamptz,implementation:()=>new Date(),impure:true});const {Pool}=mem.adapters.createPg();const pool=new Pool(),db=createStore(pool);let time=L.weekDeadline(1)-1;
 const auth=createAccounts({db,secure:false,now:()=>time,ownerEmail:()=> 'owner@example.test',ownerToken:()=> 'private-setup'});const h=createHandlers({db,auth,now:()=>time});
 const request=async(handler,action,body,cookie='',headers={})=>{let status,data;const out={};await handler({url:'/api/test',method:body===undefined?'GET':'POST',query:typeof action==='string'?{action}:action,body,headers:{host:'localhost',origin:'http://localhost','x-lms-request':'1',cookie,...headers}}, {setHeader:(k,v)=>out[k]=v,status(n){status=n;return this;},json(v){data=v;}});return {status,data,cookie:out['Set-Cookie']?.split(';')[0],headers:out};};
 const post=(action,body,cookie)=>request(auth.handler,action,body,cookie);const pw='several memorable words here';
 assert.equal((await post('signup',{email:'missing-name@example.test',password:'1234567'})).status,400);
 assert.equal((await post('signup',{email:'short-password@example.test',firstName:'Short',lastName:'Password',password:'123456'})).status,400);
 assert.equal((await post('signup',{email:'seven-characters@example.test',firstName:'Seven',lastName:'Characters',password:'1234567'})).status,200);
 assert.equal((await post('signup',{email:'owner@example.test',firstName:'Test',lastName:'Owner',password:pw})).status,400);
 const owner=await post('signup',{email:'owner@example.test',firstName:'Test',lastName:'Owner',password:pw,setupToken:'private-setup'});assert.equal(owner.status,200,JSON.stringify(owner.data));assert.equal(owner.data.user.role,'owner');assert.equal(owner.data.user.name,'Test Owner');assert.match(owner.headers['Set-Cookie'],/HttpOnly/);
 const member=await post('signup',{email:'player@example.test',firstName:'Test',lastName:'Player',password:pw,role:'owner'});assert.equal(member.status,200,JSON.stringify(member.data));assert.equal(member.data.user.role,'member');assert.equal(member.data.user.name,'Test Player');
 assert.equal((await post('name',{userId:member.data.user.id,firstName:'Changed',lastName:'Member'},member.cookie)).status,403);
 await db.mutate(S=>S.entries.push({id:'manual-entry',code:'manual-code',name:'Manual member',email:'stranger@example.test',label:'',paid:false,created:time}));
 const stranger=await post('signup',{email:'stranger@example.test',firstName:'Manual',lastName:'Member',password:pw});assert.equal(stranger.status,200);
 assert.equal((await request(auth.handler,'me',undefined,stranger.cookie)).data.entries.length,1);
 assert.equal((await db.read()).entries.find(e=>e.id==='manual-entry').accountId,null);
 assert.equal((await post('assign',{entryId:'manual-entry',userId:stranger.data.user.id},member.cookie)).status,403);
 assert.equal((await post('assign',{entryId:'manual-entry',userId:stranger.data.user.id},owner.cookie)).status,200);
 assert.equal((await request(h.me,{entryId:'manual-entry'},undefined,stranger.cookie)).status,200);
 assert.equal((await request(auth.handler,'members',undefined,member.cookie)).status,403);
 assert.equal((await request(auth.handler,'logout',{},member.cookie,{origin:'https://evil.test'})).status,403);
 assert.equal((await request(auth.handler,'logout',{},member.cookie,{'x-lms-request':''})).status,403);
 assert.equal((await request(h.adminState,{}, {},member.cookie)).status,401);
 assert.equal((await request(h.state,{},undefined,'',{'x-admin-key':'private-setup'})).data.admin,false);
 let me=(await request(auth.handler,'me',undefined,member.cookie)).data;assert.equal(me.entries.length,1);const id=me.entries[0].id;assert.equal(me.entries[0].label,'1');
 const extra=await post('entry',{},member.cookie);assert.equal(extra.status,200);me=(await request(auth.handler,'me',undefined,member.cookie)).data;assert.equal(me.entries.length,2);assert.deepEqual(me.entries.map(e=>e.label),['1','2']);const extraId=extra.data.entryId;
 assert.equal((await request(h.pick,{}, {entryId:extraId,week:1,team:L.gamesByWeek(1)[0].home},member.cookie)).data.error,'unpaid');
 const pick=team=>request(h.pick,{}, {entryId:id,week:1,team},member.cookie);
 assert.equal((await pick(L.gamesByWeek(1)[0].home)).data.error,'unpaid');
 assert.equal((await request(h.pick,{}, {entryId:id,week:1,team:'SEA'},stranger.cookie)).data.error,'unknown_code');
 assert.equal((await request(h.me,{entryId:id},undefined,stranger.cookie)).status,404);
 let state=(await request(h.state,{},undefined,owner.cookie)).data;state.entries.find(e=>e.id===id).paid=true;
 let paid=await request(h.adminState,{}, {...state,baseRevision:state.revision},owner.cookie);assert.equal(paid.status,200,JSON.stringify(paid.data));
 await db.withClient(c=>c.query('UPDATE accounts SET name=$1 WHERE id=$2',['Test',member.data.user.id]));
 assert.equal((await pick(L.gamesByWeek(1)[0].home)).data.error,'name_required');
 await db.withClient(c=>c.query('UPDATE accounts SET name=$1 WHERE id=$2',['Test Player',member.data.user.id]));
 assert.equal((await pick(L.gamesByWeek(1)[0].home)).status,200);
 const latestPick=L.gamesByWeek(1).at(-1).home;assert.equal((await pick(latestPick)).status,200);
 const memberPickView=await request(h.me,{entryId:id},undefined,member.cookie);assert.equal(memberPickView.data.picks[1],latestPick);assert.equal(memberPickView.data.state.picks[id][1],'HIDDEN');
 const memberId=member.data.user.id,memberEntryIds=me.entries.map(e=>e.id);assert.equal((await post('name',{userId:memberId,firstName:'Taylor',lastName:'Player'},owner.cookie)).status,200);
 const renamedMember=(await request(auth.handler,'me',undefined,member.cookie)).data;assert.equal(renamedMember.user.id,memberId);assert.equal(renamedMember.user.name,'Taylor Player');assert.deepEqual(renamedMember.entries.map(e=>e.id),memberEntryIds);
 const afterRename=await db.read();assert.ok(afterRename.entries.filter(e=>e.accountId===memberId).every(e=>e.name==='Taylor Player'));assert.equal(afterRename.picks[id][1],latestPick);assert.equal(afterRename.entries.find(e=>e.id===id).paid,true);
 const publicAfterRename=(await request(h.state,{},undefined,'')).data;assert.equal(JSON.stringify(publicAfterRename).includes(memberId),false);assert.ok(publicAfterRename.entries.every(e=>e.accountId===undefined));
 const ownerEntry=(await request(auth.handler,'me',undefined,owner.cookie)).data.entries[0].id;
 state=(await request(h.state,{},undefined,owner.cookie)).data;state.entries.find(e=>e.id===ownerEntry).paid=true;
 const ownerPaid=await request(h.adminState,{}, {...state,baseRevision:state.revision},owner.cookie);assert.equal(ownerPaid.status,200);
 const ownerPickView=await request(h.me,{entryId:ownerEntry},undefined,owner.cookie);assert.equal(ownerPickView.data.entry.paid,true);assert.equal(ownerPickView.data.state.picks[id][1],latestPick);assert.equal(ownerPickView.data.state.admin,false);
 time=L.weekDeadline(1);assert.equal((await pick(null)).data.error,'locked');assert.equal((await pick(L.gamesByWeek(1).at(-1).away)).data.error,'locked');
 assert.equal((await request(h.adminPick,{}, {entryId:id,week:1,team:L.gamesByWeek(1)[0].home},owner.cookie)).status,200);
 assert.equal((await post('role',{userId:member.data.user.id,role:'admin'},member.cookie)).status,403);
 assert.equal((await post('role',{userId:member.data.user.id,role:'admin'},owner.cookie)).status,200);
 assert.equal((await request(auth.handler,'me',undefined,member.cookie)).data.user,null);
 const admin=await post('login',{email:'player@example.test',password:pw});assert.equal(admin.status,200);
 assert.equal((await post('name',{userId:owner.data.user.id,firstName:'Wrong',lastName:'Owner'},admin.cookie)).status,403);
 assert.equal((await post('name',{userId:stranger.data.user.id,firstName:'Only',lastName:''},admin.cookie)).status,400);
 assert.equal((await post('name',{userId:stranger.data.user.id,firstName:'Jordan',lastName:'Smith'},admin.cookie)).status,200);
 const renamedStranger=(await request(auth.handler,'me',undefined,stranger.cookie)).data;assert.equal(renamedStranger.user.id,stranger.data.user.id);assert.equal(renamedStranger.user.name,'Jordan Smith');assert.ok((await db.read()).entries.filter(e=>e.accountId===stranger.data.user.id).every(e=>e.name==='Jordan Smith'));
 const adminPickView=await request(h.me,{entryId:id},undefined,admin.cookie);assert.equal(adminPickView.data.state.picks[id][1],L.gamesByWeek(1)[0].home);
 const adminMembers=await request(auth.handler,'members',undefined,admin.cookie);assert.equal(adminMembers.status,200);assert.deepEqual(adminMembers.data.entries,[]);assert.deepEqual(adminMembers.data.audit,[]);
 assert.equal((await post('role',{userId:owner.data.user.id,role:'member'},owner.cookie)).status,403);
 assert.equal((await post('reset-link',{userId:owner.data.user.id},admin.cookie)).status,403);
 const reset=await post('reset-link',{userId:stranger.data.user.id},admin.cookie);assert.equal(reset.status,200);
 const newpw='another longer memorable password';assert.equal((await post('reset',{token:reset.data.resetToken,password:newpw})).status,200);
 assert.equal((await post('reset',{token:reset.data.resetToken,password:newpw})).status,400);
 assert.equal((await post('login',{email:'stranger@example.test',password:pw})).status,401);
 const relog=await post('login',{email:'stranger@example.test',password:newpw});assert.equal(relog.status,200);
 assert.equal((await post('disable',{userId:stranger.data.user.id,disabled:true},owner.cookie)).status,200);
 assert.equal((await request(auth.handler,'me',undefined,relog.cookie)).data.user,null);
 assert.equal((await post('login',{email:'stranger@example.test',password:newpw})).status,401);
 const records=(await db.withClient(c=>c.query('SELECT password_hash FROM accounts'))).rows;assert.ok(records.every(a=>!a.password_hash.includes(pw)));
 const audit=(await request(auth.handler,'members',undefined,owner.cookie)).data.audit;assert.ok(audit.some(a=>a.action==='account.role'));assert.ok(audit.some(a=>a.action==='competition./api/test'));
 const changed=await post('password',{currentPassword:pw,password:'new private owner password'},owner.cookie);assert.equal(changed.status,200);assert.equal((await request(auth.handler,'me',undefined,owner.cookie)).data.user,null);owner.cookie=changed.cookie;
 for(let i=0;i<12;i++)await post('login',{email:'missing@example.test',password:'wrong'});assert.equal((await post('login',{email:'missing@example.test',password:'wrong'})).status,429);
 await post('logout',{},owner.cookie);assert.equal((await request(auth.handler,'me',undefined,owner.cookie)).data.user,null);
 await pool.end();
});
