const {test}=require('node:test');const assert=require('node:assert/strict');const {newDb,DataType}=require('pg-mem');
const {createStore}=require('../api/_db');const {createAccounts}=require('../lib/accounts');const {createHandlers}=require('../lib/api');const {L}=require('./helpers');
test('accounts: immediate signup, owner protection, permissions, payment, picks, reset, sessions and audit',async()=>{
 const mem=newDb();mem.public.registerFunction({name:'clock_timestamp',returns:DataType.timestamptz,implementation:()=>new Date(),impure:true});const {Pool}=mem.adapters.createPg();const pool=new Pool(),db=createStore(pool);let time=L.weekDeadline(1)-1;
 const auth=createAccounts({db,secure:false,now:()=>time,ownerEmail:()=> 'owner@example.test',ownerToken:()=> 'private-setup'});const h=createHandlers({db,auth,now:()=>time});
 const request=async(handler,action,body,cookie='',headers={})=>{let status,data;const out={};await handler({url:'/api/test',method:body===undefined?'GET':'POST',query:typeof action==='string'?{action}:action,body,headers:{host:'localhost',origin:'http://localhost','x-lms-request':'1',cookie,...headers}}, {setHeader:(k,v)=>out[k]=v,status(n){status=n;return this;},json(v){data=v;}});return {status,data,cookie:out['Set-Cookie']?.split(';')[0],headers:out};};
 const post=(action,body,cookie)=>request(auth.handler,action,body,cookie);const pw='several memorable words here';
 assert.equal((await post('signup',{email:'missing-name@example.test',password:'1234567'})).status,400);
 assert.equal((await post('signup',{email:'short-password@example.test',firstName:'Short',lastName:'Password',password:'123456'})).status,400);
 const spectator=await post('signup',{email:'seven-characters@example.test',firstName:'Seven',lastName:'Characters',password:'1234567'});assert.equal(spectator.status,200);
 assert.equal((await post('participation',{status:'not_participating'},spectator.cookie)).status,200);assert.equal((await request(auth.handler,'me',undefined,spectator.cookie)).data.participation,'not_participating');
 const spectatorEntry=(await post('entry',{},spectator.cookie)).data.entryId;assert.equal((await request(auth.handler,'me',undefined,spectator.cookie)).data.participation,'not_entered');
 assert.equal((await post('remove-entry',{entryId:spectatorEntry},spectator.cookie)).status,200);assert.equal((await request(auth.handler,'me',undefined,spectator.cookie)).data.entries.length,0);
 assert.equal((await post('signup',{email:'owner@example.test',firstName:'Test',lastName:'Owner',password:pw})).status,400);
 const owner=await post('signup',{email:'owner@example.test',firstName:'Test',lastName:'Owner',password:pw,setupToken:'private-setup'});assert.equal(owner.status,200,JSON.stringify(owner.data));assert.equal(owner.data.user.role,'owner');assert.equal(owner.data.user.name,'Test Owner');assert.match(owner.headers['Set-Cookie'],/HttpOnly/);
 await db.withClient(c=>c.query("UPDATE accounts SET role='member' WHERE id=$1",[owner.data.user.id]));const repairedOwner=await request(auth.handler,'me',undefined,owner.cookie);assert.equal(repairedOwner.data.user.role,'owner');
 const member=await post('signup',{email:'player@example.test',firstName:'Test',lastName:'Player',password:pw,role:'owner'});assert.equal(member.status,200,JSON.stringify(member.data));assert.equal(member.data.user.role,'member');assert.equal(member.data.user.name,'Test Player');
 assert.equal((await post('view-as',{userId:owner.data.user.id},member.cookie)).status,403);assert.equal((await post('view-as-stop',{},member.cookie)).status,403);
 const viewMember=await post('view-as',{userId:member.data.user.id},owner.cookie);assert.equal(viewMember.status,200);let ownerViewing=await request(auth.handler,'me',undefined,owner.cookie);assert.equal(ownerViewing.data.user.id,member.data.user.id);assert.equal(ownerViewing.data.user.role,'member');assert.equal(ownerViewing.data.impersonation.owner.id,owner.data.user.id);assert.equal(ownerViewing.data.impersonation.member.id,member.data.user.id);assert.equal((await request(auth.handler,'members',undefined,owner.cookie)).status,403);assert.equal((await request(h.adminState,{}, {},owner.cookie)).status,401);assert.equal((await post('view-as-stop',{},owner.cookie)).status,200);ownerViewing=await request(auth.handler,'me',undefined,owner.cookie);assert.equal(ownerViewing.data.user.id,owner.data.user.id);assert.equal(ownerViewing.data.impersonation,null);
 assert.equal((await post('name',{userId:member.data.user.id,firstName:'Changed',lastName:'Member'},member.cookie)).status,403);
 await db.mutate(S=>S.entries.push({id:'manual-entry',code:'manual-code',name:'Manual member',email:'stranger@example.test',label:'',paid:false,created:time}));
 const stranger=await post('signup',{email:'stranger@example.test',firstName:'Manual',lastName:'Member',password:pw});assert.equal(stranger.status,200);
 assert.equal((await request(auth.handler,'me',undefined,stranger.cookie)).data.entries.length,0);
 assert.equal((await db.read()).entries.find(e=>e.id==='manual-entry').accountId,null);
 assert.equal((await post('assign',{entryId:'manual-entry',userId:stranger.data.user.id},member.cookie)).status,403);
 assert.equal((await post('assign',{entryId:'manual-entry',userId:stranger.data.user.id},owner.cookie)).status,200);
 assert.equal((await request(h.me,{entryId:'manual-entry'},undefined,stranger.cookie)).status,200);
 assert.equal((await request(auth.handler,'members',undefined,member.cookie)).status,403);
 assert.equal((await request(auth.handler,'logout',{},member.cookie,{origin:'https://evil.test'})).status,403);
 assert.equal((await request(auth.handler,'logout',{},member.cookie,{'x-lms-request':''})).status,403);
 assert.equal((await request(h.adminState,{}, {},member.cookie)).status,401);
 assert.equal((await request(h.adminPick,{}, {entryId:'manual-entry',week:1,team:L.gamesByWeek(1)[0].home},member.cookie)).status,401);
 assert.equal((await request(h.state,{},undefined,'',{'x-admin-key':'private-setup'})).data.admin,false);
 let me=(await request(auth.handler,'me',undefined,member.cookie)).data;assert.equal(me.entries.length,0);assert.equal(me.participation,'not_entered');
 const first=await post('entry',{},member.cookie);assert.equal(first.status,200);const id=first.data.entryId;
 const extra=await post('entry',{},member.cookie);assert.equal(extra.status,200);me=(await request(auth.handler,'me',undefined,member.cookie)).data;assert.equal(me.entries.length,2);assert.deepEqual(me.entries.map(e=>e.label),['1','2']);assert.deepEqual(me.entries.map(e=>e.rolloverPayments),[{},{}]);assert.equal(me.summary.participating,2);const extraId=extra.data.entryId;
 assert.equal((await request(h.pick,{}, {entryId:extraId,week:1,team:L.gamesByWeek(1)[0].home},member.cookie)).data.error,'unpaid');
 assert.equal((await post('remove-entry',{entryId:extraId},member.cookie)).status,200);assert.equal((await request(auth.handler,'me',undefined,member.cookie)).data.entries.length,1);
 const pick=team=>request(h.pick,{}, {entryId:id,week:1,team},member.cookie);
 assert.equal((await pick(L.gamesByWeek(1)[0].home)).data.error,'unpaid');
 assert.equal((await request(h.pick,{}, {entryId:id,week:1,team:'SEA'},stranger.cookie)).data.error,'unknown_code');
 assert.equal((await request(h.me,{entryId:id},undefined,stranger.cookie)).status,404);
 let state=(await request(h.state,{},undefined,owner.cookie)).data;state.entries.find(e=>e.id===id).paid=true;
 let paid=await request(h.adminState,{}, {...state,baseRevision:state.revision},owner.cookie);assert.equal(paid.status,200,JSON.stringify(paid.data));
 assert.equal((await post('remove-entry',{entryId:id},member.cookie)).status,400);assert.equal((await post('participation',{status:'not_participating'},member.cookie)).status,400);
 await db.withClient(c=>c.query('UPDATE accounts SET name=$1 WHERE id=$2',['Test',member.data.user.id]));
 assert.equal((await pick(L.gamesByWeek(1)[0].home)).data.error,'name_required');
 await db.withClient(c=>c.query('UPDATE accounts SET name=$1 WHERE id=$2',['Test Player',member.data.user.id]));
 assert.equal((await post('view-as',{userId:member.data.user.id},owner.cookie)).status,200);assert.equal((await post('password',{currentPassword:pw,password:'should not replace member password'},owner.cookie)).status,403);const takeoverTeam=L.gamesByWeek(1)[0].home;assert.equal((await request(h.pick,{}, {entryId:id,week:1,team:takeoverTeam},owner.cookie)).status,200);assert.equal((await post('view-as-stop',{},owner.cookie)).status,200);
 assert.equal((await pick(L.gamesByWeek(1)[0].home)).status,200);
 const latestPick=L.gamesByWeek(1).at(-1).home;assert.equal((await pick(latestPick)).status,200);
 const memberPickView=await request(h.me,{entryId:id},undefined,member.cookie);assert.equal(memberPickView.data.picks[1],latestPick);assert.equal(memberPickView.data.state.picks[id][1],'HIDDEN');
 const memberId=member.data.user.id,memberEntryIds=[id];assert.equal((await post('name',{userId:memberId,firstName:'Taylor',lastName:'Player'},owner.cookie)).status,200);
 const renamedMember=(await request(auth.handler,'me',undefined,member.cookie)).data;assert.equal(renamedMember.user.id,memberId);assert.equal(renamedMember.user.name,'Taylor Player');assert.deepEqual(renamedMember.entries.map(e=>e.id),memberEntryIds);
 const afterRename=await db.read();assert.ok(afterRename.entries.filter(e=>e.accountId===memberId).every(e=>e.name==='Taylor Player'));assert.equal(afterRename.picks[id][1],latestPick);assert.equal(afterRename.entries.find(e=>e.id===id).paid,true);
 const publicAfterRename=(await request(h.state,{},undefined,'')).data;assert.equal(JSON.stringify(publicAfterRename).includes(memberId),false);assert.ok(publicAfterRename.entries.every(e=>e.accountId===undefined));
 const ownerEntry=(await post('entry',{},owner.cookie)).data.entryId;
 state=(await request(h.state,{},undefined,owner.cookie)).data;state.entries.find(e=>e.id===ownerEntry).paid=true;
 const ownerPaid=await request(h.adminState,{}, {...state,baseRevision:state.revision},owner.cookie);assert.equal(ownerPaid.status,200);
 const ownerPickView=await request(h.me,{entryId:ownerEntry},undefined,owner.cookie);assert.equal(ownerPickView.data.entry.paid,true);assert.equal(ownerPickView.data.state.picks[id][1],latestPick);assert.equal(ownerPickView.data.state.admin,false);
 time=L.weekDeadline(1);assert.equal((await pick(null)).data.error,'locked');assert.equal((await pick(L.gamesByWeek(1).at(-1).away)).data.error,'locked');
 assert.equal((await request(h.adminPick,{}, {entryId:id,week:1,team:L.gamesByWeek(1)[0].home},owner.cookie)).status,200);
 assert.equal((await post('role',{userId:member.data.user.id,role:'admin'},member.cookie)).status,403);
 assert.equal((await post('role',{userId:member.data.user.id,role:'admin'},owner.cookie)).status,200);
 const promotedSession=await request(auth.handler,'me',undefined,member.cookie);assert.equal(promotedSession.data.user.role,'admin');
 assert.equal((await post('view-as',{userId:member.data.user.id},owner.cookie)).status,200);const ownerViewingAdmin=await request(auth.handler,'me',undefined,owner.cookie);assert.equal(ownerViewingAdmin.data.user.role,'admin');assert.equal(ownerViewingAdmin.data.impersonation.member.role,'admin');assert.equal((await request(h.state,{},undefined,owner.cookie)).data.admin,true);assert.equal((await post('view-as-stop',{},owner.cookie)).status,200);
 const admin=await post('login',{email:'player@example.test',password:pw});assert.equal(admin.status,200);assert.equal(admin.data.user.role,'admin');
 assert.equal((await post('view-as',{userId:stranger.data.user.id},admin.cookie)).status,403);
 const adminLateTeam=L.gamesByWeek(1).flatMap(g=>[g.home,g.away]).find(team=>L.teamGame(team,2));const adminLatePick=await request(h.adminPick,{}, {entryId:'manual-entry',week:1,team:adminLateTeam},admin.cookie);assert.equal(adminLatePick.status,200);assert.equal((await db.read()).picks['manual-entry'][1],adminLateTeam);
 assert.equal((await request(h.adminPick,{}, {entryId:'manual-entry',week:2,team:adminLateTeam},admin.cookie)).data.error,'used');
 const allTeams=[...new Set(L.GAMES.flatMap(g=>[g.home,g.away]))],byeTeam=allTeams.find(team=>!L.teamGame(team,5));assert.ok(byeTeam);assert.equal((await request(h.adminPick,{}, {entryId:'manual-entry',week:5,team:byeTeam},admin.cookie)).data.error,'bye');
 state=(await request(h.state,{},undefined,admin.cookie)).data;state.entries.find(e=>e.id==='manual-entry').paid=true;const adminPaidEntry=await request(h.adminState,{}, {...state,baseRevision:state.revision},admin.cookie);assert.equal(adminPaidEntry.status,200);assert.equal((await db.read()).entries.find(e=>e.id==='manual-entry').paid,true);
 const forbiddenSettings=structuredClone((await request(h.state,{},undefined,admin.cookie)).data),originalFee=forbiddenSettings.settings.fee;forbiddenSettings.settings.fee=originalFee+5;const settingsDenied=await request(h.adminState,{}, {...forbiddenSettings,baseRevision:forbiddenSettings.revision},admin.cookie);assert.equal(settingsDenied.status,403);assert.equal(settingsDenied.data.error,'owner_required');assert.equal((await db.read()).settings.fee,originalFee);
 const forbiddenRestore=structuredClone((await request(h.state,{},undefined,admin.cookie)).data);forbiddenRestore.replacePicks={};const restoreDenied=await request(h.adminState,{}, {...forbiddenRestore,baseRevision:forbiddenRestore.revision},admin.cookie);assert.equal(restoreDenied.status,403);assert.equal(restoreDenied.data.error,'owner_required');
 const ownerSettings=structuredClone((await request(h.state,{},undefined,owner.cookie)).data);ownerSettings.settings.fee=originalFee+1;const ownerSettingsSaved=await request(h.adminState,{}, {...ownerSettings,baseRevision:ownerSettings.revision},owner.cookie);assert.equal(ownerSettingsSaved.status,200);assert.equal((await db.read()).settings.fee,originalFee+1);
 assert.equal((await post('participation',{userId:stranger.data.user.id,status:'not_participating'},admin.cookie)).status,400);
 state=(await request(h.state,{},undefined,admin.cookie)).data;state.entries.find(e=>e.id==='manual-entry').paid=false;const adminUnpaidEntry=await request(h.adminState,{}, {...state,baseRevision:state.revision},admin.cookie);assert.equal(adminUnpaidEntry.status,200);assert.equal((await post('participation',{userId:stranger.data.user.id,status:'not_participating'},admin.cookie)).status,200);assert.equal((await request(auth.handler,'me',undefined,stranger.cookie)).data.participation,'not_participating');assert.equal((await db.read()).entries.some(e=>e.id==='manual-entry'),false);
 assert.equal((await post('name',{userId:owner.data.user.id,firstName:'Wrong',lastName:'Owner'},admin.cookie)).status,403);
 assert.equal((await post('name',{userId:stranger.data.user.id,firstName:'Only',lastName:''},admin.cookie)).status,400);
 assert.equal((await post('name',{userId:stranger.data.user.id,firstName:'Jordan',lastName:'Smith'},admin.cookie)).status,200);
 const renamedStranger=(await request(auth.handler,'me',undefined,stranger.cookie)).data;assert.equal(renamedStranger.user.id,stranger.data.user.id);assert.equal(renamedStranger.user.name,'Jordan Smith');assert.ok((await db.read()).entries.filter(e=>e.accountId===stranger.data.user.id).every(e=>e.name==='Jordan Smith'));
 const adminPickView=await request(h.me,{entryId:id},undefined,admin.cookie);assert.equal(adminPickView.data.state.picks[id][1],L.gamesByWeek(1)[0].home);
 const adminMembers=await request(auth.handler,'members',undefined,admin.cookie);assert.equal(adminMembers.status,200);assert.deepEqual(adminMembers.data.entries,[]);assert.deepEqual(adminMembers.data.audit,[]);
 assert.equal((await post('role',{userId:owner.data.user.id,role:'member'},owner.cookie)).status,403);
 assert.equal((await post('reset-link',{userId:owner.data.user.id},admin.cookie)).status,403);
 const reset=await post('reset-link',{userId:stranger.data.user.id},admin.cookie);assert.equal(reset.status,200);
 const newpw='another longer memorable password';assert.equal((await post('reset',{token:reset.data.resetToken,password:newpw})).status,200);
 assert.equal((await post('reset',{token:reset.data.resetToken,password:newpw})).status,400);
 assert.equal((await post('login',{email:'stranger@example.test',password:pw})).status,401);
 const relog=await post('login',{email:'stranger@example.test',password:newpw});assert.equal(relog.status,200);
 assert.equal((await post('disable',{userId:stranger.data.user.id,disabled:true},owner.cookie)).status,200);
 assert.equal((await request(auth.handler,'me',undefined,relog.cookie)).data.user,null);
 assert.equal((await post('login',{email:'stranger@example.test',password:newpw})).status,401);
 const records=(await db.withClient(c=>c.query('SELECT password_hash FROM accounts'))).rows;assert.ok(records.every(a=>!a.password_hash.includes(pw)));
 const audit=(await request(auth.handler,'members',undefined,owner.cookie)).data.audit;assert.ok(audit.some(a=>a.action==='account.role'));assert.ok(audit.some(a=>a.action==='account.view_as_start'&&a.actor_id===owner.data.user.id&&a.target_id===member.data.user.id));assert.ok(audit.some(a=>a.action==='account.view_as_stop'&&a.actor_id===owner.data.user.id));assert.ok(audit.some(a=>a.action==='competition./api/test'));assert.ok(audit.some(a=>a.action==='competition./api/test'&&a.actor_id===owner.data.user.id&&a.details.viewedAccountId===member.data.user.id));const overrideAudit=audit.find(a=>a.action==='competition.admin_pick'&&a.target_id==='manual-entry');assert.equal(overrideAudit.details.deadlineOverridden,true);assert.equal(overrideAudit.details.week,1);assert.equal(overrideAudit.details.team,adminLateTeam);
 const changed=await post('password',{currentPassword:pw,password:'new private owner password'},owner.cookie);assert.equal(changed.status,200);assert.equal((await request(auth.handler,'me',undefined,owner.cookie)).data.user,null);owner.cookie=changed.cookie;
 for(let i=0;i<12;i++)await post('login',{email:'missing@example.test',password:'wrong'});assert.equal((await post('login',{email:'missing@example.test',password:'wrong'})).status,429);
 await post('logout',{},owner.cookie);assert.equal((await request(auth.handler,'me',undefined,owner.cookie)).data.user,null);
 await pool.end();
});
