const {test}=require('node:test');const assert=require('node:assert/strict');
const {createTeamInfoHandler}=require('../lib/team-info');
const team={team:{displayName:'Seattle Seahawks',shortDisplayName:'Seahawks',location:'Seattle',slug:'seattle-seahawks',color:'002a5c',alternateColor:'69be28',logos:[{href:'logo.png',rel:['default']}],record:{items:[{type:'total',summary:'1-0'}]},standingSummary:'1st in NFC West',links:[{href:'https://www.espn.com/seahawks',rel:['clubhouse']}],franchise:{venue:{fullName:'Lumen Field',grass:false,indoor:false,address:{city:'Seattle',state:'WA'},images:[{href:'venue.jpg'}]}}}};
const roster={coach:[{firstName:'Mike',lastName:'Macdonald'}],athletes:[{position:'offense',items:[{fullName:'Sam Darnold',jersey:'14',position:{abbreviation:'QB'},status:{type:'active',name:'Active'}}]},{position:'injuredReserveOrOut',items:[{fullName:'Example Player',jersey:'1',position:{abbreviation:'WR'},status:{type:'day-to-day',name:'Day-To-Day'}}]}]};
const event=(id,season,date,abbr,mine,theirs,completed=true,week='Week 1')=>({id,season:{year:season},date,week:{text:week},competitions:[{status:{type:{completed}},venue:{fullName:'Lumen Field'},competitors:[{homeAway:'home',team:{abbreviation:'SEA',displayName:'Seattle Seahawks'},score:String(mine)},{homeAway:'away',team:{abbreviation:abbr,displayName:abbr==='NE'?'New England Patriots':'San Francisco 49ers'},score:String(theirs)}]}]});
const current={events:[event('current',2026,'2026-09-10T00:20:00Z','NE',24,17,true),event('next',2026,'2026-09-20T20:25:00Z','SF',0,0,false,'Week 2')],team:{recordSummary:'1-0',standingSummary:'1st in NFC West'}};
const previous={events:[event('previous',2025,'2025-12-28T21:00:00Z','SF',27,10,true,'Week 17')]};
const postseason={events:[event('post',2025,'2026-02-08T23:30:00Z','NE',29,13,true,'Super Bowl')]};
const statistics={results:{stats:{categories:[{name:'passing',stats:[{name:'totalPointsPerGame',displayValue:'28.4'},{name:'yardsPerGame',displayValue:'351.2'},{name:'passingYardsPerGame',displayValue:'228.1'}]},{name:'rushing',stats:[{name:'rushingYardsPerGame',displayValue:'123.3'}]},{name:'miscellaneous',stats:[{name:'thirdDownConvPct',displayValue:'39.8'},{name:'redzoneTouchdownPct',displayValue:'54.2'},{name:'turnOverDifferential',displayValue:'-3'}]},{name:'defensive',stats:[{name:'sacks',displayValue:'47'}]}]}}};
function response(data){return {ok:true,json:async()=>structuredClone(data)};}
function call(handler,{method='GET',team='SEA'}={}){let status,body;const headers={};return handler({method,query:{team}},{setHeader:(key,value)=>headers[key]=value,status(value){status=value;return this;},json(value){body=value;}}).then(()=>({status,body,headers}));}
test('team information combines live profile, form, fixtures, roster and prior-season context',async()=>{
 const fetchImpl=async url=>response(url.endsWith('/roster')?roster:url.includes('schedule?season=2026')?current:url.includes('schedule?season=2025&seasontype=3')?postseason:url.includes('schedule?season=2025')?previous:url.includes('/statistics?')?statistics:team);
 const result=await call(createTeamInfoHandler({fetchImpl,now:()=>Date.parse('2026-09-11T12:00:00Z')}));
 assert.equal(result.status,200);assert.equal(result.body.team.name,'Seattle Seahawks');assert.equal(result.body.team.headCoach,'Mike Macdonald');assert.equal(result.body.team.venue.name,'Lumen Field');assert.equal(result.body.team.division,'NFC West');assert.equal(result.body.current.record,'1-0');assert.equal(result.body.recent[0].result,'W');assert.equal(result.body.upcoming[0].opponent.abbr,'SF');assert.equal(result.body.previous.record,'1-0');assert.equal(result.body.previous.postseasonRecord,'1-0');assert.equal(result.body.previous.postseasonFinish.week,'Super Bowl');assert.equal(result.body.roster.positions.QB[0].name,'Sam Darnold');assert.equal(result.body.roster.availability[0].status,'Day-To-Day');assert.ok(result.body.previous.statistics.some(([label,value])=>label==='Third-down rate'&&value==='39.8%'));assert.match(result.headers['Cache-Control'],/s-maxage=900/);assert.equal(JSON.stringify(result.body).includes('athletes'),false);
});
test('team information validates the team and method before fetching',async()=>{let fetched=0;const handler=createTeamInfoHandler({fetchImpl:async()=>{fetched++;return response({});}});assert.equal((await call(handler,{team:'XYZ'})).status,400);assert.equal((await call(handler,{method:'POST'})).status,405);assert.equal(fetched,0);});
