let accountUser=null,accountEntries=[],accountPage=['/login','/signup','/dashboard','/admin','/reset-password'].includes(location.pathname)?location.pathname:null;
const accountCall=(action,body)=>apiRequest('/api/account?action='+action,body);
function accountBar(){if(location.protocol==='file:')return '';return `<div class="row account-bar"><a class="btn" href="/">Standings</a>${accountUser?`<a class="btn" href="/dashboard">My dashboard</a>${['owner','admin'].includes(accountUser.role)?'<a class="btn" href="/admin">Admin area</a>':''}<button class="btn" onclick="accountLogout()">Sign out</button>`:'<a class="btn" href="/login">Sign in</a><a class="btn gold" href="/signup">Join the competition</a>'}</div>`+adminNavigation();}
const adminSections=[['adminhome','Admin home'],['entries','Entries & payments'],['members','Members & roles'],['picks','Manage picks'],['results','Results'],['settings','Settings'],['dash','Overview']];
function adminNavigation(){return accountPage==='/admin'&&ADMIN?`<div class="admin-nav" role="navigation" aria-label="Admin tools">${adminSections.map(([view,label])=>`<button class="btn ${S.ui.view===view?'gold':''}" aria-current="${S.ui.view===view?'page':'false'}" onclick="setView('${view}')">${view==='members'&&accountUser?.role!=='owner'?'Members':label}</button>`).join('')}</div>`:'';}
function renderAdminHome(r,comp){
 const paid=S.entries.filter(e=>entryPaid(e,r,comp)).length;
 const tools=[['entries','Entries & payments','Mark fees as paid, add people manually and import entries.'],['members',accountUser?.role==='owner'?'Members & roles':'Members',accountUser?.role==='owner'?'Assign admins, manage access, link entries and reset passwords.':'View members and reset member passwords.'],['picks','Manage picks','Add or change picks for any member, including corrections after the deadline.'],['results','Results','Fetch scores, enter results and settle the week.'],['settings','Competition settings','Manage rounds, rules, entry fees and backups.'],['dash','Competition overview','Check the prize pot, standings, missing picks and fixtures.']];
 return `<div class="card admin-intro"><div class="kick">${accountUser?.role==='owner'?'Owner':'Administrator'} access</div><h1>Admin area</h1><p>Manage your competition here. Your own entry and picks are in <a href="/dashboard">My dashboard</a>.</p><div class="row"><span class="pill">Round ${r.n}</span><span class="pill paid">${paid} paid</span><span class="pill unpaid">${S.entries.length-paid} awaiting payment</span></div></div><div class="admin-tools">${tools.map(([view,label,description])=>`<button class="card admin-tool" onclick="setView('${view}')"><strong>${label}</strong><span>${description}</span><span class="admin-tool-open">Open →</span></button>`).join('')}</div>${deadlineBanner(defaultWeek())}`;
}

function deadlineBanner(w){const d=L.weekDeadline(w);return `<div class="card deadline"><b>Week ${w} pick deadline: ${d?new Date(d).toLocaleString('en-GB',{weekday:'long',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/London'}):'Awaiting fixtures'} (UK time)</b><div class="small muted">All picks and changes close one hour before the first kick-off.${d&&d<=serverNow()?' This week is now locked.':''}</div></div>`;}
function remoteHeader(){return `<div class="stat pub" onclick="location.href='${accountUser?'/dashboard':'/login'}'"><div class="v" style="font-size:18px">${accountUser?'Account':'Sign in'}</div><div class="l">${accountUser?esc(accountUser.role):'join / login'}</div></div>`;}
async function remoteAdmin(){location.href=accountUser&&['admin','owner'].includes(accountUser.role)?'/admin':'/login';}
async function accountLogout(){try{await flushRemote();await remoteQueue;if(remoteDirty)return;await accountCall('logout',{});location.href='/';}catch(e){toast(esc(e.message));}}
function authForm(){
 const signup=accountPage==='/signup',reset=accountPage==='/reset-password';
 document.body.classList.add('ro');document.getElementById('nav').classList.add('hidden');document.getElementById('hdrStats').innerHTML='';document.getElementById('foot').textContent='Manual payments. Play responsibly. 18+.';
 document.getElementById('main').innerHTML=accountBar()+`<div class="card auth-card"><h2>${reset?'Set a new password':signup?'Join Last Man Standing':'Welcome back'}</h2><p class="muted">${reset?'Your reset link works once and expires after one hour.':signup?'Create your account and you’re in. No confirmation email. The organiser will activate your entry once you have paid.':'Sign in to manage your weekly picks.'}</p><form id="accountForm">${reset?'':`${signup?'<label>Your name <span class="muted">(optional)</span><input type="text" name="name" autocomplete="name" maxlength="100"></label>':''}<label>Email address<input name="email" type="email" autocomplete="email" required maxlength="320" ${signup&&location.hash.startsWith('#setup=')?'value="roboshea@gmail.com"':''}></label>`}<label>Password<input name="password" type="password" autocomplete="${signup||reset?'new-password':'current-password'}" ${signup||reset?'minlength="12"':''} maxlength="256" required></label>${signup||reset?'<p class="small muted">At least 12 characters. A few memorable words work well.</p>':''}<p id="accountError" role="alert"></p><button class="btn gold" type="submit">${reset?'Save password':signup?'Create account':'Sign in'}</button></form><p>${reset?'<a href="/login">Back to sign in</a>':signup?'Already registered? <a href="/login">Sign in</a>':'New here? <a href="/signup">Create an account</a>'}</p>${!signup&&!reset?'<details><summary>Forgotten your password?</summary><p>Contact the organiser for a private password reset link.</p></details>':''}</div>`;
 document.getElementById('accountForm').onsubmit=async event=>{
  event.preventDefault();const form=event.currentTarget,button=form.querySelector('button'),error=document.getElementById('accountError');button.disabled=true;error.textContent='';
  try{const body=Object.fromEntries(new FormData(form));if(signup)body.setupToken=new URLSearchParams(location.hash.slice(1)).get('setup');if(reset)body.token=new URLSearchParams(location.hash.slice(1)).get('token');await accountCall(reset?'reset':signup?'signup':'login',body);history.replaceState(null,'',location.pathname);location.href=reset?'/login':'/dashboard';}catch(e){error.textContent=e.message;button.disabled=false;}
 };
}
async function accountBoot(){
 const data=await accountCall('me');accountUser=data.user;accountEntries=data.entries;
 if(['/login','/signup','/reset-password'].includes(accountPage)){authForm();return true;}
 if(accountPage==='/dashboard'||location.pathname.startsWith('/play/')){
  if(!accountUser){location.replace('/login');return true;}
  if(!accountEntries.length){document.getElementById('main').innerHTML=accountBar()+'<div class="card"><h2>Your entries</h2><p>You have no entries yet.</p><button class="btn gold" onclick="addAccountEntry()">Add an entry</button></div>';return true;}
  PLAYER_CODE=accountEntries.find(e=>e.id===new URLSearchParams(location.search).get('entry'))?.id||accountEntries[0].id;
 }
 if(accountPage==='/admin'&&(!accountUser||!['owner','admin'].includes(accountUser.role))){location.replace('/login');return true;}
 return false;
}
function memberTools(){return accountBar()+`<div class="card"><h2>My account <span class="tag">${esc(accountUser?.email||'')}</span></h2><div class="row"><label>Entry <select onchange="location.href='/dashboard?entry='+encodeURIComponent(this.value)">${accountEntries.map(e=>`<option value="${esc(e.id)}" ${e.id===PLAYER_CODE?'selected':''}>${esc(e.name+(e.label?' - '+e.label:''))}</option>`).join('')}</select></label><button class="btn" onclick="addAccountEntry()">Add another entry</button><button class="btn" onclick="changeAccountPassword()">Change password</button></div></div>`;}
async function addAccountEntry(){try{const data=await accountCall('entry',{});location.href='/dashboard?entry='+encodeURIComponent(data.entryId);}catch(e){toast(esc(e.message));}}
function changeAccountPassword(){
 modal('<h2>Change password</h2>'+ `<form id="passwordForm"><label>Current password<input name="currentPassword" type="password" autocomplete="current-password" required></label><label>New password<input name="password" type="password" autocomplete="new-password" minlength="12" maxlength="256" required></label><p id="passwordError" role="alert"></p><button class="btn gold">Save password</button></form>`);
 document.getElementById('passwordForm').onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');btn.disabled=true;try{await accountCall('password',Object.fromEntries(new FormData(e.currentTarget)));closeModal();toast('Password updated. Other sessions have been signed out.');}catch(error){document.getElementById('passwordError').textContent=error.message;btn.disabled=false;}};
}
async function renderMembers(){
 try{const data=await accountCall('members');
 const owner=accountUser.role==='owner';
 const ownerPanels=owner?`<div class="card"><h2>Connect entries to accounts</h2>${data.entries.length?data.entries.map(e=>`<div class="row" style="margin-bottom:12px"><b>${esc(e.name)} ${esc(e.label||'')}</b><select aria-label="Account for ${esc(e.name)}" onchange="assignEntry('${e.id}',this.value)"><option value="">${e.accountId?'Choose account':'Managed manually'}</option>${data.users.filter(u=>!u.disabled).map(u=>`<option value="${u.id}" ${e.accountId===u.id?'selected':''}>${esc(u.email)}</option>`).join('')}</select></div>`).join(''):'<p>No entries yet.</p>'}</div><div class="card"><h2>Recent admin activity</h2>${data.audit.map(a=>`<p class="small">${esc(new Date(a.created_at).toLocaleString('en-GB',{timeZone:'Europe/London'}))} · ${esc(data.users.find(u=>u.id===a.actor_id)?.name||'System')} · ${esc(a.action)}${a.target_id?' · '+esc(data.entries.find(e=>e.id===a.target_id)?.name||data.users.find(u=>u.id===a.target_id)?.email||'Entry'):''}</p>`).join('')||'<p>No activity yet.</p>'}</div>`:'';
 document.getElementById('main').innerHTML=accountBar()+`<div class="card"><h2>${owner?'Members and roles':'Members'}</h2><p class="muted">${owner?'Use Entries to add people manually and mark payments. Link an entry below only after checking who it belongs to. Members sign up without email confirmation.':'Use Entries & payments to add people and mark fees as paid. Members sign up without email confirmation.'}</p><div class="tablewrap"><table><thead><tr><th>Member</th><th>Role</th><th>Access</th><th>Actions</th></tr></thead><tbody>${data.users.map(u=>`<tr><td>${esc(u.name)}<br><span class="small muted">${esc(u.email)}</span></td><td>${owner&&u.role!=='owner'?`<select aria-label="Role for ${esc(u.name)}" onchange="memberAction('role','${u.id}',{role:this.value})"><option ${u.role==='member'?'selected':''}>member</option><option ${u.role==='admin'?'selected':''}>admin</option></select>`:esc(u.role)}</td><td>${u.disabled?'Disabled':'Enabled'}</td><td>${u.role!=='owner'&&(owner||u.role==='member')?`<button class="btn sm" onclick="memberAction('reset-link','${u.id}')">Reset password</button>`:''}${owner&&u.role!=='owner'?` <button class="btn sm" onclick="memberAction('disable','${u.id}',{disabled:${!u.disabled}})">${u.disabled?'Enable':'Disable'}</button>`:''}</td></tr>`).join('')}</tbody></table></div></div>${ownerPanels}`;
 }catch(e){toast(esc(e.message));}
}
async function memberAction(action,userId,extra={}){try{const data=await accountCall(action,{userId,...extra});if(data.resetToken){modal('<h2>Private password reset link</h2>'+ `<p>Send this link privately to the member. It expires in one hour and works once.</p><input id="resetLink" readonly value="${esc(location.origin+'/reset-password#token='+data.resetToken)}"><button class="btn" onclick="copyText(document.getElementById('resetLink').value)">Copy link</button>`);}else await renderMembers();}catch(e){toast(esc(e.message));}}
async function assignEntry(entryId,userId){if(!userId)return;try{await accountCall('assign',{entryId,userId});applyRemote(await apiRequest('/api/state'));toast('Entry connected.');}catch(e){toast(esc(e.message));}await renderMembers();}
