let accountUser=null,accountEntries=[],accountPage=['/login','/signup','/dashboard','/account','/admin','/reset-password','/help','/privacy'].includes(location.pathname)?location.pathname:null;
const accountCall=(action,body)=>apiRequest('/api/account?action='+action,body);
function accountBar(){if(location.protocol==='file:')return '';if(accountPage==='/admin')return adminNavigation();return ['/login','/signup','/reset-password'].includes(accountPage)?'<div class="row account-bar"><a class="btn" href="/">Dashboard</a></div>':'';}
const adminSections=[['adminhome','Admin home'],['entries','Entries & payments'],['members','Members & roles'],['picks','Manage picks'],['results','Results'],['settings','Settings'],['dash','Overview'],['adminhelp','Admin guide']];
function adminNavigation(){return accountPage==='/admin'&&ADMIN?`<div class="admin-nav" role="navigation" aria-label="Admin tools">${adminSections.map(([view,label])=>`<button class="btn ${S.ui.view===view?'gold':''}" aria-current="${S.ui.view===view?'page':'false'}" onclick="setView('${view}')">${view==='members'&&accountUser?.role!=='owner'?'Members':label}</button>`).join('')}</div>`:'';}
function renderAdminHome(r,comp){
 const paid=S.entries.filter(e=>entryPaid(e,r,comp)).length;
 const tools=[['entries','Entries & payments',accountUser?.role==='owner'?'Mark payments, add people manually and use the owner-only spreadsheet importer.':'Mark payments and add individual entries. New members should register and set their own password.'],['members',accountUser?.role==='owner'?'Members & roles':'Members',accountUser?.role==='owner'?'Correct names, assign admins, manage access, link entries and reset passwords.':'Correct member names and reset member passwords.'],['picks','Manage picks','Add or change picks for any member, including corrections after the deadline.'],['results','Results','Fetch scores, enter results and settle the week.'],['settings','Competition settings','Manage rounds, rules, entry fees and backups.'],['dash','Competition overview','Check the prize pot, standings, missing picks and fixtures.'],['adminhelp','Admin how-to guide','Search the complete guide to payments, accounts, picks, results, rollovers and settings.']];
 return `<div class="card admin-intro"><div class="kick">${accountUser?.role==='owner'?'Owner':'Administrator'} access</div><h1>Admin area</h1><p>Manage your competition here. Your own entry and picks are in <a href="/dashboard">My dashboard</a>, with password and entry controls in <a href="/account">Account settings</a>.</p><div class="row"><span class="pill">Round ${r.n}</span><span class="pill paid">${paid} paid</span><span class="pill unpaid">${S.entries.length-paid} awaiting payment</span></div></div><div class="admin-tools">${tools.map(([view,label,description])=>`<button class="card admin-tool" onclick="setView('${view}')"><strong>${label}</strong><span>${description}</span><span class="admin-tool-open">Open →</span></button>`).join('')}</div>${deadlineBanner(defaultWeek())}`;
}

function deadlineBanner(w){const d=L.weekDeadline(w);return `<div class="card deadline"><b>Week ${w} pick deadline: ${d?new Date(d).toLocaleString('en-GB',{weekday:'long',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/London'}):'Awaiting fixtures'} (UK time)</b><div class="small muted">All picks and changes close one hour before the first kick-off.${d&&d<=serverNow()?' This week is now locked.':''}</div></div>`;}
function remoteHeader(){
 if(!accountUser)return '<a class="stat pub" style="color:inherit;font:inherit;text-decoration:none" href="/signup"><div class="v" style="font-size:18px">Register</div><div class="l">or sign in</div></a>';
 const staff=['owner','admin'].includes(accountUser.role),inAdmin=accountPage==='/admin';
 return `<a class="stat pub" style="color:inherit;font:inherit;text-decoration:none" href="${staff?(inAdmin?'/dashboard':'/admin'):'/account'}"><div class="v" style="font-size:18px">${staff?(inAdmin?'Exit admin':'Admin'):'Account'}</div><div class="l">${staff?(inAdmin?'dashboard':accountUser.role):'settings'}</div></a><button type="button" class="stat pub" style="color:inherit;font:inherit" onclick="accountLogout()"><div class="v" style="font-size:18px">Sign out</div><div class="l">account</div></button>`;
}
async function remoteAdmin(){location.href=accountUser&&['admin','owner'].includes(accountUser.role)?'/admin':'/login';}
async function accountLogout(){try{await flushRemote();await remoteQueue;if(remoteDirty)return;await accountCall('logout',{});location.href='/';}catch(e){toast(esc(e.message));}}
function authForm(){
 const signup=accountPage==='/signup',reset=accountPage==='/reset-password';
 document.body.classList.add('ro');document.getElementById('nav').classList.add('hidden');document.getElementById('hdrStats').innerHTML='';document.getElementById('foot').textContent='Manual payments. Play responsibly. 18+.';
 const tabs=reset?'':`<div class="auth-tabs"><a class="${signup?'active':''}" href="/signup">Register</a><a class="${!signup?'active':''}" href="/login">Sign in</a></div>`;
 const registerPrompt=!signup&&!reset?'<div class="register-prompt"><div><span>New player?</span><strong>Register before you sign in</strong><p>Create your NFL LMS account with your first name, last name, email and password.</p></div><a class="btn gold" href="/signup">Create my account</a></div><div class="auth-divider"><span>Already registered? Sign in below</span></div>':'';
 document.getElementById('main').innerHTML=accountBar()+`<div class="card auth-card">${tabs}${registerPrompt}<h2>${reset?'Set a new password':signup?'Register for NFL LMS':'Member sign in'}</h2><p class="muted">${reset?'Your reset link works once and expires after one hour.':signup?'Enter your first name, last name, email address and a password. Registration is immediate, with no confirmation email. Your entry becomes active after payment is approved.':'Use the email address and password you registered with.'}</p><form id="accountForm">${reset?'':`${signup?'<div class="auth-name-grid"><label>First name<input type="text" name="firstName" autocomplete="given-name" maxlength="50" required></label><label>Last name<input type="text" name="lastName" autocomplete="family-name" maxlength="50" required></label></div>':''}<label>Email address<input name="email" type="email" autocomplete="email" required maxlength="320" ${signup&&location.hash.startsWith('#setup=')?'value="roboshea@gmail.com"':''}></label>`}<label>Password<input name="password" type="password" autocomplete="${signup||reset?'new-password':'current-password'}" ${signup||reset?'minlength="7"':''} maxlength="256" required></label>${signup||reset?'<p class="small muted">At least 7 characters.</p>':''}<p id="accountError" role="alert"></p><button class="btn gold auth-submit" type="submit">${reset?'Save password':signup?'Register and create account':'Sign in'}</button></form><p>${reset?'<a href="/login">Back to sign in</a>':signup?'Already have an account? <a href="/login"><strong>Sign in here</strong></a>':''}</p><p><a href="/help">How to use NFL LMS</a></p>${!signup&&!reset?'<details><summary>Forgotten your password?</summary><p>Contact the organiser for a private password reset link.</p></details>':''}</div>`;
 document.getElementById('accountForm').onsubmit=async event=>{
  event.preventDefault();const form=event.currentTarget,button=form.querySelector('button'),error=document.getElementById('accountError');button.disabled=true;error.textContent='';
  try{const body=Object.fromEntries(new FormData(form));if(signup)body.setupToken=new URLSearchParams(location.hash.slice(1)).get('setup');if(reset)body.token=new URLSearchParams(location.hash.slice(1)).get('token');await accountCall(reset?'reset':signup?'signup':'login',body);history.replaceState(null,'',location.pathname);location.href=reset?'/login':'/dashboard';}catch(e){error.textContent=e.message;button.disabled=false;}
 };
}
async function accountBoot(){
 const data=await accountCall('me');accountUser=data.user;accountEntries=data.entries;document.getElementById('homeBrand').href=accountUser?'/dashboard':'/';
 if(['/login','/signup','/reset-password'].includes(accountPage)){authForm();return true;}
 if(accountPage==='/dashboard'||accountPage==='/account'||location.pathname.startsWith('/play/')){
  if(!accountUser){location.replace('/login');return true;}
  if(accountPage==='/dashboard'||accountPage==='/account'||location.pathname.startsWith('/play/')){
   PLAYER_CODE=accountEntries.find(e=>e.id===new URLSearchParams(location.search).get('entry'))?.id||accountEntries[0]?.id||null;
   const requestedView=new URLSearchParams(location.search).get('view');if(accountPage==='/dashboard'&&['dash','picks','results','standings'].includes(requestedView))S.ui.view=requestedView;
  }
 }
 if(accountPage==='/admin'&&(!accountUser||!['owner','admin'].includes(accountUser.role))){location.replace('/login');return true;}
 return false;
}
function memberEntrySwitcher(){
 if(accountEntries.length<2)return '';
 return `<div class="account-entry-switch"><div class="small muted">Manage an entry</div><div class="account-entry-tabs" role="navigation" aria-label="Choose competition entry">${accountEntries.map((e,i)=>`<a class="btn ${e.id===PLAYER_CODE?'gold':''}" aria-current="${e.id===PLAYER_CODE?'page':'false'}" href="/account?entry=${encodeURIComponent(e.id)}">${esc(`${accountUser?.name||e.name} ${e.label||i+1}`)}</a>`).join('')}</div><p class="small muted">Each entry has its own payment status, picks and history.</p></div>`;
}
function memberTools(){return `<div class="card account-identity"><div><div class="help-kicker">My account</div><h1>${esc(accountUser?.name||'Member')}</h1><div class="muted">${esc(accountUser?.email||'')}</div></div><div class="account-actions"><button class="btn" onclick="addAccountEntry()">${accountEntries.length?'Add another entry':'Add first entry'}</button><button class="btn" onclick="changeAccountPassword()">Change password</button><a class="btn" href="/help">How to use the app</a><a class="btn gold" href="/dashboard${PLAYER_CODE?'?entry='+encodeURIComponent(PLAYER_CODE):''}">Dashboard</a></div>${memberEntrySwitcher()}</div>`;}
function noEntryBanner(){
 if(!accountUser||accountEntries.length)return '';
 const staff=['owner','admin'].includes(accountUser.role);
 return `<div class="card"><div class="kick">Your account</div><h2>No competition entry yet</h2><p>Your sign-in is working, but there is no playing entry linked to this account. Add your first entry to join the current round. An admin must then mark it paid before it can make a pick.</p><div class="row"><button class="btn gold" onclick="addAccountEntry()">Add first entry</button>${staff?'<a class="btn" href="/admin">Open Admin area</a>':''}<a class="btn" href="/account">Account settings</a></div></div>`;
}
function accountHistory(e,r,comp){
 const weeks=[];for(let w=r.startWeek;w<=Math.min(defaultWeek(),roundEndWeek(r));w++)if(playerMe?.picks?.[w])weeks.push(w);
 return `<div class="card"><h2>Your pick history <span class="tag">Round ${r.n}</span></h2>${weeks.length?`<div class="account-history">${weeks.map(w=>{const team=playerMe.picks[w],result=teamResult(team,w),label=result.code==='W'?'Won':result.code==='L'||result.code==='BYE'?'Lost':result.code==='T'?'Tied':'Awaiting result';return `<div class="account-history-row"><span class="account-week">Week ${w}</span>${teamChip(team)}<span class="pill ${result.code==='W'?'alive':result.code==='L'||result.code==='BYE'?'out':'pending'}">${label}</span></div>`;}).join('')}</div>`:'<div class="empty">No picks made yet.</div>'}</div>`;
}
function accountTeamDirectory(e,r,comp,w){
 const usedForChoice=usedTeams(e.id,r,comp,w),pickedSinceReset=new Set(Object.entries(playerMe?.picks||{}).filter(([week])=>+week>=comp.resetWeek).map(([,team])=>team));
 const available=playerLock(w)?[]:TEAM_LIST.filter(t=>{const game=teamGame(t.abbr,w);return game&&!usedForChoice[t.abbr]&&new Date(game.date).getTime()>serverNow()&&!S.results[game.id]?.final;});
 const left=TEAM_LIST.filter(t=>!pickedSinceReset.has(t.abbr));
 const cards=list=>`<div class="account-team-grid">${list.map(t=>{const game=teamGame(t.abbr,w);return `<div class="account-team-card">${logoImg(t.abbr,'logo lg')}<div><b>${esc(t.short)}</b>${game?`<span>${game.home===t.abbr?'vs '+TEAMS[game.away].short:'@ '+TEAMS[game.home].short}</span>`:''}</div></div>`;}).join('')}</div>`;
 return `<div class="card"><h2>Available to pick in Week ${w} <span class="tag">${available.length} teams</span></h2><p class="muted small">Playing this week, not previously used since the last reset, and still available before kick-off.</p>${available.length?cards(available):'<div class="empty">No teams are currently available.</div>'}</div><div class="card"><h2>Teams you have left <span class="tag">${left.length} of 32</span></h2><p class="muted small">Every team you have not selected since the last rollover or new round, including teams on a bye this week.</p>${left.length?cards(left):'<div class="empty">No unused teams remain.</div>'}</div>`;
}
function renderAccountPage(){
 document.body.classList.add('ro','player');document.getElementById('nav').classList.remove('hidden');const r=currentRound(),comp=computeRound(r),w=defaultWeek();renderHeader(r,comp);document.querySelectorAll('nav button').forEach(b=>b.classList.remove('active'));
 if(!playerMe){document.getElementById('main').innerHTML=memberTools()+(!accountEntries.length?noEntryBanner():`<div class="card"><p>${esc(playerError||'Loading your competition entry…')}</p></div>`);return;}
 const e=playerMe.entry,entryIndex=Math.max(0,accountEntries.findIndex(item=>item.id===e.id)),entryTitle=`${accountUser?.name||e.name} ${e.label||entryIndex+1}`,paid=entryPaid(e,r,comp),alive=comp.alive.has(e.id),pick=playerMe.picks[w],game=pick?teamGame(pick,w):null,locked=playerLock(w),eligible=isAliveForWeek(comp,w,e.id)&&!comp.complete,fullName=/\S+\s+\S+/.test(accountUser?.name||'');
 const status=paid&&alive?'Active':!paid?'Inactive · payment required':'Eliminated';
 const pickAction=!fullName?'<span class="pill out">Full name required</span>':paid&&eligible&&!locked?`<a class="btn gold" href="/dashboard?entry=${encodeURIComponent(e.id)}&view=picks">${pick?'Change pick':'Make your pick'}</a>`:`<span class="pill ${locked?'pending':'out'}">${locked?'Picks locked':!paid?'Payment required':'Not eligible to pick'}</span>`;
 const current=`<div class="grid two account-summary"><div class="card" style="margin:0"><h2>${esc(entryTitle)} <span class="tag">Round ${r.n}</span></h2><div class="account-status ${paid&&alive?'active':'inactive'}">${status}</div><p>${!fullName?'Ask an administrator to add your first and last name before you make a pick.':paid?'Payment confirmed for this entry.':'Contact Connor or Havo to pay. An admin must mark this entry paid before it can make a pick.'}</p></div><div class="card" style="margin:0"><h2>Current pick <span class="tag">Week ${w}</span></h2>${pick?`<div class="account-current-pick">${logoImg(pick,'logo xl')}<div><strong>${esc(TEAMS[pick].name)}</strong>${game?`<span>${TEAMS[game.away].short} @ ${TEAMS[game.home].short} · ${fmtDate(game.date)}</span>`:''}</div></div>`:'<p class="muted">No selection confirmed for this week.</p>'}<div class="row" style="margin-top:14px">${pickAction}</div></div></div>`;
 document.getElementById('main').innerHTML=announcementBanner()+memberTools()+deadlineBanner(w)+current+accountHistory(e,r,comp)+accountTeamDirectory(e,r,comp,w);const foot=document.getElementById('foot');if(foot)foot.textContent='Your NFL LMS account and competition entry.';
}
async function addAccountEntry(){try{const data=await accountCall('entry',{});location.href=(accountPage==='/account'?'/account?entry=':'/dashboard?entry=')+encodeURIComponent(data.entryId);}catch(e){toast(esc(e.message));}}
function changeAccountPassword(){
 modal('<h2>Change password</h2>'+ `<form id="passwordForm"><label>Current password<input name="currentPassword" type="password" autocomplete="current-password" required></label><label>New password<input name="password" type="password" autocomplete="new-password" minlength="7" maxlength="256" required></label><p class="small muted">At least 7 characters.</p><p id="passwordError" role="alert"></p><button class="btn gold">Save password</button></form>`);
 document.getElementById('passwordForm').onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');btn.disabled=true;try{await accountCall('password',Object.fromEntries(new FormData(e.currentTarget)));closeModal();toast('Password updated. Other sessions have been signed out.');}catch(error){document.getElementById('passwordError').textContent=error.message;btn.disabled=false;}};
}
async function renderMembers(){
 try{const data=await accountCall('members');
 const owner=accountUser.role==='owner';
 const nameEditor=u=>{const parts=u.name.trim().split(/\s+/),first=parts.shift()||'',last=parts.join(' '),editable=owner||u.role!=='owner';return editable?`<div class="member-name-editor"><input id="first-${u.id}" aria-label="First name for ${esc(u.name)}" value="${esc(first)}" placeholder="First name" maxlength="50"><input id="last-${u.id}" aria-label="Last name for ${esc(u.name)}" value="${esc(last)}" placeholder="Last name required" maxlength="50" required><button class="btn sm" onclick="saveMemberName('${u.id}')">Save name</button></div>${!last?'<div class="small name-required">Last name required</div>':''}`:`<b>${esc(u.name)}</b>`;};
 const ownerPanels=owner?`<div class="card"><h2>Connect entries to accounts</h2>${data.entries.length?data.entries.map(e=>`<div class="row" style="margin-bottom:12px"><b>${esc(e.name)} ${esc(e.label||'')}</b><select aria-label="Account for ${esc(e.name)}" onchange="assignEntry('${e.id}',this.value)"><option value="">${e.accountId?'Choose account':'Managed manually'}</option>${data.users.filter(u=>!u.disabled).map(u=>`<option value="${u.id}" ${e.accountId===u.id?'selected':''}>${esc(u.email)}</option>`).join('')}</select></div>`).join(''):'<p>No entries yet.</p>'}</div><div class="card"><h2>Recent admin activity</h2>${data.audit.map(a=>`<p class="small">${esc(new Date(a.created_at).toLocaleString('en-GB',{timeZone:'Europe/London'}))} · ${esc(data.users.find(u=>u.id===a.actor_id)?.name||'System')} · ${esc(a.action)}${a.target_id?' · '+esc(data.entries.find(e=>e.id===a.target_id)?.name||data.users.find(u=>u.id===a.target_id)?.email||'Entry'):''}</p>`).join('')||'<p>No activity yet.</p>'}</div>`:'';
 document.getElementById('main').innerHTML=accountBar()+`<div class="card"><h2>${owner?'Members and roles':'Members'}</h2><p class="muted">Every account needs a first name, last name and email address. Saving a name correction updates every entry owned by that member; their hidden member ID keeps payments, picks and history connected.</p><div class="tablewrap"><table><thead><tr><th>First and last name</th><th>Email address</th><th>Role</th><th>Access</th><th>Actions</th></tr></thead><tbody>${data.users.map(u=>`<tr><td>${nameEditor(u)}</td><td>${esc(u.email)}</td><td>${owner&&u.role!=='owner'?`<select aria-label="Role for ${esc(u.name)}" onchange="memberAction('role','${u.id}',{role:this.value})"><option ${u.role==='member'?'selected':''}>member</option><option ${u.role==='admin'?'selected':''}>admin</option></select>`:esc(u.role)}</td><td>${u.disabled?'Disabled':'Enabled'}</td><td>${u.role!=='owner'&&(owner||u.role==='member')?`<button class="btn sm" onclick="memberAction('reset-link','${u.id}')">Reset password</button>`:''}${owner&&u.role!=='owner'?` <button class="btn sm" onclick="memberAction('disable','${u.id}',{disabled:${!u.disabled}})">${u.disabled?'Enable':'Disable'}</button>`:''}</td></tr>`).join('')}</tbody></table></div></div>${ownerPanels}`;
 }catch(e){toast(esc(e.message));}
}
async function saveMemberName(userId){const firstName=document.getElementById('first-'+userId)?.value||'',lastName=document.getElementById('last-'+userId)?.value||'';try{await accountCall('name',{userId,firstName,lastName});applyRemote(await apiRequest('/api/state'));await renderMembers();toast('Member name updated.');}catch(e){toast(esc(e.message));}}
async function memberAction(action,userId,extra={}){try{const data=await accountCall(action,{userId,...extra});if(data.resetToken){modal('<h2>Private password reset link</h2>'+ `<p>Send this link privately to the member. It expires in one hour and works once.</p><input id="resetLink" readonly value="${esc(location.origin+'/reset-password#token='+data.resetToken)}"><button class="btn" onclick="copyText(document.getElementById('resetLink').value)">Copy link</button>`);}else await renderMembers();}catch(e){toast(esc(e.message));}}
async function assignEntry(entryId,userId){if(!userId)return;try{await accountCall('assign',{entryId,userId});applyRemote(await apiRequest('/api/state'));toast('Entry connected.');}catch(e){toast(esc(e.message));}await renderMembers();}
