let accountUser=null,accountEntries=[],accountParticipation='not_entered',accountSummary=null,accountPage=['/login','/signup','/dashboard','/account','/admin','/reset-password','/help','/privacy'].includes(location.pathname)?location.pathname:null;
const accountCall=(action,body)=>apiRequest('/api/account?action='+action,body);
function accountBar(){if(location.protocol==='file:')return '';if(accountPage==='/admin')return adminNavigation();return ['/login','/signup','/reset-password'].includes(accountPage)?'<div class="row account-bar"><a class="btn" href="/">Dashboard</a></div>':'';}
const adminSections=[['adminhome','Admin home'],['entries','Entries & payments'],['members','Members & roles'],['picks','Manage picks'],['results','Results'],['settings','Settings'],['dash','Overview'],['adminhelp','Admin guide']];
function adminNavigation(){return accountPage==='/admin'&&ADMIN?`<div class="admin-nav" role="navigation" aria-label="Admin tools">${adminSections.map(([view,label])=>`<button class="btn ${S.ui.view===view?'gold':''}" aria-current="${S.ui.view===view?'page':'false'}" onclick="setView('${view}')">${view==='members'&&accountUser?.role!=='owner'?'Members':label}</button>`).join('')}<a class="btn admin-exit" href="/dashboard">Exit admin</a></div>`:'';}
function renderAdminHome(r,comp){
 const entries=roundEntries(r),paid=entries.filter(e=>entryPaid(e,r,comp)).length,missing=missingEntries(defaultWeek(),r,comp).length,summary=accountSummary||{members:0,participating:0,entries:entries.length,paid,unpaid:entries.length-paid};
 const tools=[['entries','Entries & payments',accountUser?.role==='owner'?'Mark payments, add people manually and use the owner-only spreadsheet importer.':'Mark payments and add individual entries. New members should register and set their own password.'],['members',accountUser?.role==='owner'?'Members & roles':'Members',accountUser?.role==='owner'?'Correct names, assign admins, manage access, link entries and reset passwords.':'Correct member names and reset member passwords.'],['picks','Manage picks','Add, replace or clear picks for any entry, including your own and deadline overrides.'],['results','Results','Fetch scores, enter results and settle the week.'],['settings','Competition settings','Manage rounds, rules, entry fees and backups.'],['dash','Competition overview','Check the prize pot, standings, missing picks and fixtures.'],['adminhelp','Admin how-to guide','Search the complete guide to payments, accounts, picks, results, rollovers and settings.']];
 return `<div class="card admin-intro"><div class="kick">${accountUser?.role==='owner'?'Owner':'Administrator'} access</div><h1>Admin area</h1><p>Manage the competition here. Use <a href="/dashboard">Dashboard</a> for your own entries and picks, just like every other member.</p>${participationSummary(summary,missing)}</div><div class="admin-tools">${tools.map(([view,label,description])=>`<button class="card admin-tool" onclick="setView('${view}')"><strong>${label}</strong><span>${description}</span><span class="admin-tool-open">Open →</span></button>`).join('')}</div>${deadlineBanner(defaultWeek())}`;
}
function participationSummary(summary,missing){return `<div class="participation-summary"><div><b>${summary.members}</b><span>Members</span></div><div><b>${summary.participating}</b><span>Participating</span></div><div class="paid"><b>${summary.paid}</b><span>Round entries</span></div><div class="unpaid"><b>${summary.unpaid}</b><span>Awaiting payment</span></div><div class="topick"><b>${missing}</b><span>Still to pick</span></div></div>`;}

function deadlineBanner(w){const d=L.weekDeadline(w);return `<div class="card deadline"><b>Week ${w} pick deadline: ${d?new Date(d).toLocaleString('en-GB',{weekday:'long',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/London'}):'Awaiting fixtures'} (UK time)</b><div class="small muted">All picks and changes close one hour before the first kick-off.${d&&d<=serverNow()?' This week is now locked.':''}</div></div>`;}
function remoteHeader(){
 if(!accountUser)return '<a class="stat pub" style="color:inherit;font:inherit;text-decoration:none" href="/login"><div class="v" style="font-size:18px">Sign in</div><div class="l">account</div></a>';
 const inAccount=accountPage==='/account';
 return `<a class="stat pub account-access" href="${inAccount?'/dashboard':'/account'}"><div class="v">${inAccount?'Exit account settings':'Account'}</div><div class="l">${esc(accountUser.name)}</div></a><button type="button" class="stat pub signout-access" onclick="accountLogout()"><div class="v">Sign out</div><div class="l">account</div></button>`;
}
async function remoteAdmin(){location.href=accountUser&&['admin','owner'].includes(accountUser.role)?'/admin':'/login';}
async function accountLogout(){try{await flushRemote();await remoteQueue;if(remoteDirty)return;await accountCall('logout',{});location.href='/';}catch(e){toast(esc(e.message));}}
function authForm(){
 const signup=accountPage==='/signup',reset=accountPage==='/reset-password';
 document.body.classList.add('ro');document.getElementById('nav').classList.add('hidden');document.getElementById('hdrStats').innerHTML='';document.getElementById('foot').textContent='Manual payments. Play responsibly. 18+.';
 const tabs=reset?'':`<div class="auth-tabs"><a class="${signup?'active':''}" href="/signup">Register</a><a class="${!signup?'active':''}" href="/login">Sign in</a></div>`;
 const registerPrompt=!signup&&!reset?'<div class="register-prompt"><div><span>New player?</span><strong>Register before you sign in</strong><p>Create your NFL LMS account with your first name, last name, email and password.</p></div><a class="btn gold" href="/signup">Create my account</a></div><div class="auth-divider"><span>Already registered? Sign in below</span></div>':'';
 document.getElementById('main').innerHTML=accountBar()+`<div class="card auth-card">${tabs}${registerPrompt}<h2>${reset?'Set a new password':signup?'Register for NFL LMS':'Member sign in'}</h2><p class="muted">${reset?'Your reset link works once and expires after one hour.':signup?'Enter your first name, last name, email address and a password. Registration is immediate, with no confirmation email. After registering, use Dashboard to add an entry if you want to join the current round.':'Use the email address and password you registered with.'}</p><form id="accountForm">${reset?'':`${signup?'<div class="auth-name-grid"><label>First name<input type="text" name="firstName" autocomplete="given-name" maxlength="50" required></label><label>Last name<input type="text" name="lastName" autocomplete="family-name" maxlength="50" required></label></div>':''}<label>Email address<input name="email" type="email" autocomplete="email" required maxlength="320" ${signup&&location.hash.startsWith('#setup=')?'value="roboshea@gmail.com"':''}></label>`}<label>Password<input name="password" type="password" autocomplete="${signup||reset?'new-password':'current-password'}" ${signup||reset?'minlength="7"':''} maxlength="256" required></label>${signup||reset?'<p class="small muted">At least 7 characters.</p>':''}<p id="accountError" role="alert"></p><button class="btn gold auth-submit" type="submit">${reset?'Save password':signup?'Register and create account':'Sign in'}</button></form><p>${reset?'<a href="/login">Back to sign in</a>':signup?'Already have an account? <a href="/login"><strong>Sign in here</strong></a>':''}</p><p><a href="/help">How to use NFL LMS</a></p>${!signup&&!reset?'<details><summary>Forgotten your password?</summary><p>Contact the organiser for a private password reset link.</p></details>':''}</div>`;
 document.getElementById('accountForm').onsubmit=async event=>{
  event.preventDefault();const form=event.currentTarget,button=form.querySelector('button'),error=document.getElementById('accountError');button.disabled=true;error.textContent='';
  try{const body=Object.fromEntries(new FormData(form));if(signup)body.setupToken=new URLSearchParams(location.hash.slice(1)).get('setup');if(reset)body.token=new URLSearchParams(location.hash.slice(1)).get('token');await accountCall(reset?'reset':signup?'signup':'login',body);history.replaceState(null,'',location.pathname);location.href=reset?'/login':'/dashboard';}catch(e){error.textContent=e.message;button.disabled=false;}
 };
}
async function accountBoot(){
 const data=await accountCall('me');accountUser=data.user;accountEntries=data.entries;accountParticipation=data.participation||'not_entered';accountSummary=data.summary;document.getElementById('homeBrand').href=accountUser?'/dashboard':'/';
 if(['/login','/signup','/reset-password'].includes(accountPage)){authForm();return true;}
 if(accountPage==='/dashboard'||accountPage==='/account'||location.pathname.startsWith('/play/')){
  if(!accountUser){location.replace('/login');return true;}
  if(accountPage==='/dashboard'||accountPage==='/account'||location.pathname.startsWith('/play/')){
   PLAYER_CODE=accountEntries.find(e=>e.id===new URLSearchParams(location.search).get('entry'))?.id||accountEntries[0]?.id||null;
   const requestedView=new URLSearchParams(location.search).get('view');if(accountPage==='/dashboard'&&['dash','picks','results','standings'].includes(requestedView))S.ui.view=requestedView;
  }
 }
 if(accountPage==='/admin'&&(!accountUser||!['owner','admin'].includes(accountUser.role))){location.replace('/login');return true;}
 return false;
}
function memberEntrySwitcher(){
 if(accountEntries.length<2)return '';
 const base=accountPage==='/account'?'/account':'/dashboard';return `<div class="account-entry-switch"><div class="small muted">Choose an entry</div><div class="account-entry-tabs" role="navigation" aria-label="Choose competition entry">${accountEntries.map((e,i)=>`<a class="btn ${e.id===PLAYER_CODE?'gold':''}" aria-current="${e.id===PLAYER_CODE?'page':'false'}" href="${base}?entry=${encodeURIComponent(e.id)}">${esc(`${accountUser?.name||e.name} ${e.label||i+1}`)}</a>`).join('')}</div><p class="small muted">Each entry has its own payment status, pick and history.</p></div>`;
}
function memberTools(){return `<div class="card account-identity"><div><div class="help-kicker">Account settings</div><h1>${esc(accountUser?.name||'Member')}</h1><div class="muted">${esc(accountUser?.email||'')}</div></div><div class="account-actions"><button class="btn" onclick="changeAccountPassword()">Change password</button><a class="btn" href="/help">How to use the app</a><a class="btn gold" href="/dashboard">Exit account settings</a></div></div>`;}
function noEntryBanner(){
 if(!accountUser||accountEntries.length)return '';
 const staff=['owner','admin'].includes(accountUser.role);
 const sittingOut=accountParticipation==='not_participating';return `<div class="card join-round"><div class="kick">Round ${currentRound().n}</div><h2>${sittingOut?'You are not participating':'Join this round'}</h2><p>${sittingOut?'You are currently marked as not participating. Add an entry whenever you decide to join.':'Your member account is ready. You are not counted as an entry until you choose to join this round.'}</p><div class="row"><button class="btn gold" onclick="addAccountEntry()">Add an entry</button>${!sittingOut?`<button class="btn" onclick="setAccountParticipation('not_participating')">I’m not participating</button>`:''}${sittingOut?`<button class="btn" onclick="setAccountParticipation('not_entered')">Clear this status</button>`:''}${staff?'<a class="btn" href="/admin">Open Admin area</a>':''}</div></div>`;
}
function memberWeekStatus(r,comp){
 if(!accountUser)return '';
 const week=defaultWeek();let state,label;
 if(accountParticipation==='not_participating'){state='sitting';label='Sitting Out';}
 else if(accountEntries.some(e=>entryPaid(e,r,comp))){state='paid';label='Paid';}
 else if(accountEntries.length){state='unpaid';label='Not Paid';}
 else return '';
 return `<button type="button" class="member-week-status ${state}" onclick="focusRoundStatus()" aria-label="Week ${week}: ${label}"><span>Week ${week}</span><strong>${label}</strong></button>`;
}
function focusRoundStatus(){document.querySelector('.entry-controls,.join-round')?.scrollIntoView({behavior:'smooth',block:'center'});}
function memberDashboardControls(e){const paid=e&&entryPaid(e),name=e?entryName(e.id):'',staff=['owner','admin'].includes(accountUser?.role);return `<div class="card entry-controls"><h2>Your round entries <span class="tag">${accountEntries.length} ${accountEntries.length===1?'entry':'entries'}</span></h2>${memberEntrySwitcher()}<div class="row"><button class="btn gold" onclick="addAccountEntry()">Add another entry</button>${e&&!paid?`<button class="btn danger" onclick="removeAccountEntry('${e.id}','${esc(name)}')">Remove this unpaid entry</button>`:''}<button class="btn" onclick="setAccountParticipation('not_participating')">Sit out this round</button>${staff?'<a class="btn" style="border-color:var(--green);background:rgba(31,191,106,.2)" href="/admin">Open Admin area</a>':''}</div><p class="small muted">Every entry must be approved and marked paid by an administrator before it can make a pick. Paid entries must be marked unpaid by an administrator before removal.</p></div>`;}
function renderAccountPage(){
 document.body.classList.add('ro','player');document.getElementById('nav').classList.remove('hidden');const r=currentRound(),comp=computeRound(r),w=defaultWeek();renderHeader(r,comp);document.querySelectorAll('nav button').forEach(b=>b.classList.remove('active'));
 document.getElementById('main').innerHTML=memberTools()+`<div class="card"><h2>Round participation</h2><p>${accountEntries.length?`You have ${accountEntries.length} ${accountEntries.length===1?'entry':'entries'} in Round ${r.n}. Manage entries and picks from your Dashboard.`:accountParticipation==='not_participating'?`You are marked as not participating in Round ${r.n}. You can join from your Dashboard.`:`You have not joined Round ${r.n}. Add an entry from your Dashboard if you want to play.`}</p><a class="btn gold" href="/dashboard">Go to Dashboard</a></div>`;const foot=document.getElementById('foot');if(foot)foot.textContent='Your NFL LMS account settings.';
}
async function addAccountEntry(){try{const data=await accountCall('entry',{});location.href=(accountPage==='/account'?'/account?entry=':'/dashboard?entry=')+encodeURIComponent(data.entryId);}catch(e){toast(esc(e.message));}}
async function removeAccountEntry(entryId,name){if(!confirm(`Remove ${name}? Its picks will also be removed.`))return;try{await accountCall('remove-entry',{entryId});location.href='/dashboard';}catch(e){toast(esc(e.message));}}
async function setAccountParticipation(status){const message=status==='not_participating'?'Sit out this round? Any unpaid entries and their picks will be removed.':'Clear your not-participating status?';if(!confirm(message))return;try{await accountCall('participation',{status});location.href='/dashboard';}catch(e){toast(esc(e.message));}}
function changeAccountPassword(){
 modal('<h2>Change password</h2>'+ `<form id="passwordForm"><label>Current password<input name="currentPassword" type="password" autocomplete="current-password" required></label><label>New password<input name="password" type="password" autocomplete="new-password" minlength="7" maxlength="256" required></label><p class="small muted">At least 7 characters.</p><p id="passwordError" role="alert"></p><button class="btn gold">Save password</button></form>`);
 document.getElementById('passwordForm').onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');btn.disabled=true;try{await accountCall('password',Object.fromEntries(new FormData(e.currentTarget)));closeModal();toast('Password updated. Other sessions have been signed out.');}catch(error){document.getElementById('passwordError').textContent=error.message;btn.disabled=false;}};
}
async function renderMembers(){
 try{const data=await accountCall('members');
 const owner=accountUser.role==='owner';
 const nameEditor=u=>{const parts=u.name.trim().split(/\s+/),first=parts.shift()||'',last=parts.join(' '),editable=owner||u.role!=='owner';return editable?`<div class="member-name-editor"><input id="first-${u.id}" aria-label="First name for ${esc(u.name)}" value="${esc(first)}" placeholder="First name" maxlength="50"><input id="last-${u.id}" aria-label="Last name for ${esc(u.name)}" value="${esc(last)}" placeholder="Last name required" maxlength="50" required><button class="btn sm" onclick="saveMemberName('${u.id}')">Save name</button></div>${!last?'<div class="small name-required">Last name required</div>':''}`:`<b>${esc(u.name)}</b>`;};
 const ownerPanels=owner?`<div class="card"><h2>Connect entries to accounts</h2>${data.entries.length?data.entries.map(e=>`<div class="row" style="margin-bottom:12px"><b>${esc(e.name)} ${esc(e.label||'')}</b><select aria-label="Account for ${esc(e.name)}" onchange="assignEntry('${e.id}',this.value)"><option value="">${e.accountId?'Choose account':'Managed manually'}</option>${data.users.filter(u=>!u.disabled).map(u=>`<option value="${u.id}" ${e.accountId===u.id?'selected':''}>${esc(u.email)}</option>`).join('')}</select></div>`).join(''):'<p>No entries yet.</p>'}</div>`:'';
 const missing=missingEntries(defaultWeek(),currentRound(),computeRound(currentRound())).length;
 document.getElementById('main').innerHTML=accountBar()+`<div class="card"><h2>${owner?'Members and roles':'Members'}</h2>${participationSummary(data.summary,missing)}<p class="muted">Members exist independently from competition entries. Only confirmed paid entries count in the current round; unpaid requests remain here for approval.</p><div class="tablewrap"><table><thead><tr><th>First and last name</th><th>Email address</th><th>Role</th><th>Round ${data.round}</th><th>Actions</th></tr></thead><tbody>${data.users.map(u=>{const status=u.participation==='participating'?`${u.entryCount} ${u.entryCount===1?'request':'requests'} · ${u.paidCount} confirmed · ${u.unpaidCount} awaiting payment`:u.participation==='not_participating'?'Not participating':'Not entered';return `<tr><td>${nameEditor(u)}</td><td>${esc(u.email)}</td><td>${owner&&u.role!=='owner'?`<select aria-label="Role for ${esc(u.name)}" onchange="memberAction('role','${u.id}',{role:this.value})"><option ${u.role==='member'?'selected':''}>member</option><option ${u.role==='admin'?'selected':''}>admin</option></select>`:esc(u.role)}</td><td><b>${status}</b></td><td><div class="row">${!u.disabled?`<button class="btn sm gold" onclick="memberAction('entry','${u.id}')">Add entry</button>`:''}${u.participation==='not_participating'?`<button class="btn sm" onclick="memberAction('participation','${u.id}',{status:'not_entered'})">Clear status</button>`:`<button class="btn sm" onclick="memberAction('participation','${u.id}',{status:'not_participating'})">Mark not participating</button>`}${u.role!=='owner'&&(owner||u.role==='member')?`<button class="btn sm" onclick="memberAction('reset-link','${u.id}')">Reset password</button>`:''}${owner&&u.role!=='owner'?`<button class="btn sm" onclick="memberAction('disable','${u.id}',{disabled:${!u.disabled}})">${u.disabled?'Enable':'Disable'}</button>`:''}</div></td></tr>`;}).join('')}</tbody></table></div></div>${ownerPanels}`;
 }catch(e){toast(esc(e.message));}
}
async function saveMemberName(userId){const firstName=document.getElementById('first-'+userId)?.value||'',lastName=document.getElementById('last-'+userId)?.value||'';try{await accountCall('name',{userId,firstName,lastName});applyRemote(await apiRequest('/api/state'));await renderMembers();toast('Member name updated.');}catch(e){toast(esc(e.message));}}
async function memberAction(action,userId,extra={}){if(action==='participation'&&extra.status==='not_participating'&&!confirm('Mark this member as not participating? Any unpaid current-round entries and their picks will be removed.'))return;try{const data=await accountCall(action,{userId,...extra});if(data.resetToken){modal('<h2>Private password reset link</h2>'+ `<p>Send this link privately to the member. It expires in one hour and works once.</p><input id="resetLink" readonly value="${esc(location.origin+'/reset-password#token='+data.resetToken)}"><button class="btn" onclick="copyText(document.getElementById('resetLink').value)">Copy link</button>`);}else{if(action==='entry'||action==='participation')applyRemote(await apiRequest('/api/state'));await renderMembers();}}catch(e){toast(esc(e.message));}}
async function assignEntry(entryId,userId){if(!userId)return;try{await accountCall('assign',{entryId,userId});applyRemote(await apiRequest('/api/state'));toast('Entry connected.');}catch(e){toast(esc(e.message));}await renderMembers();}
